name: main

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: check nix flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop '.' --command just test
  lint:
    name: lint and format flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop '.' --command just check-fmt
      - run: nix develop '.' --command just lint
